In [2]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(1,10,[2,3])
A

array([[6, 1, 4],
       [4, 8, 4]])

In [4]:
A.sum()

27

In [5]:
A.sum(axis=0)  # somme par colonne

array([10,  9,  8])

In [6]:
A.sum(axis =1)  # somme par ligne

array([11, 16])

In [7]:
A.cumsum()  # somme cumulée

array([ 6,  7, 11, 15, 23, 27])

In [8]:
A.prod()  # produit des éléments

3072

In [9]:
A.min()  # minimum des éléments

1

In [10]:
A.min(axis=0)  # minimum par colonne

array([4, 1, 4])

In [11]:
A.argmin()  # indice du minimum des éléments

1

In [12]:
A.argmin(axis = 0)

array([1, 0, 0])

In [13]:
A.sort()  # tri des éléments
A

array([[1, 4, 6],
       [4, 4, 8]])

In [14]:
A.argsort()  # indices du tri des éléments
A

array([[1, 4, 6],
       [4, 4, 8]])

In [15]:
np.exp(A)  # exponentielle des éléments

array([[2.71828183e+00, 5.45981500e+01, 4.03428793e+02],
       [5.45981500e+01, 5.45981500e+01, 2.98095799e+03]])

In [16]:
np.log(A)  # logarithme des éléments

array([[0.        , 1.38629436, 1.79175947],
       [1.38629436, 1.38629436, 2.07944154]])

In [17]:
np.cos(A)  # cosinus des éléments

array([[ 0.54030231, -0.65364362,  0.96017029],
       [-0.65364362, -0.65364362, -0.14550003]])

In [18]:
np.sinh(A)  # sinus hyperbolique des éléments

array([[1.17520119e+00, 2.72899172e+01, 2.01713157e+02],
       [2.72899172e+01, 2.72899172e+01, 1.49047883e+03]])

In [19]:
A

array([[1, 4, 6],
       [4, 4, 8]])

In [20]:
A.min()  # minimum des éléments

1

In [21]:
A.std()  # écart-type des éléments

2.140872096444188

In [22]:
A.var()  # variance des éléments

4.583333333333333

In [23]:
np.corrcoef(A)

array([[1.        , 0.80295507],
       [0.80295507, 1.        ]])

In [24]:
np.corrcoef(A)[0,1]

0.8029550685469662

In [25]:
np.unique(A, return_counts=True)  # valeurs uniques et leurs nombres d'occurrences

(array([1, 4, 6, 8]), array([1, 3, 1, 1]))

In [26]:
np.random.seed(0)
A = np.random.randint(1,10,[5,5])
A

array([[6, 1, 4, 4, 8],
       [4, 6, 3, 5, 8],
       [7, 9, 9, 2, 7],
       [8, 8, 9, 2, 6],
       [9, 5, 4, 1, 4]])

In [27]:
np.unique(A, return_counts=True) 

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 1, 5, 2, 3, 2, 4, 4]))

In [28]:
values, counts = np.unique(A, return_counts=True)
values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
counts

array([2, 2, 1, 5, 2, 3, 2, 4, 4])

In [30]:
counts.argsort()

array([2, 0, 1, 4, 6, 5, 7, 8, 3])

In [31]:
values[counts.argsort()]

array([3, 1, 2, 5, 7, 6, 8, 9, 4])

In [32]:
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f"La valeur {i} apparaît {j} fois.")

La valeur 3 apparaît 1 fois.
La valeur 1 apparaît 2 fois.
La valeur 2 apparaît 2 fois.
La valeur 5 apparaît 2 fois.
La valeur 7 apparaît 2 fois.
La valeur 6 apparaît 3 fois.
La valeur 8 apparaît 4 fois.
La valeur 9 apparaît 4 fois.
La valeur 4 apparaît 5 fois.


In [33]:
A = np.random.randn(5,5)
A[0,2] = np.nan
A[4,3] = np.nan
A

array([[-0.07770457,  1.08963016,         nan,  1.41866711,  1.16827314],
       [ 0.94718595,  1.08548703,  2.38222445, -0.40602374,  0.26644534],
       [-1.35571372, -0.11410253, -0.84423086,  0.70564081, -0.39878617],
       [-0.82719653, -0.4157447 , -0.52451219,  0.81310127, -0.22925063],
       [ 2.16171737, -0.95693143,  0.06731083,         nan, -0.45688133]])

In [34]:
np.nanmean(A)  # moyenne en ignorant les NaN

0.23906978515702657

In [35]:
np.nanvar(A)  # variance en ignorant les NaN

0.9613530732672138

In [36]:
np.nanstd(A)  # écart-type en ignorant les NaN

0.9804861412927843

In [37]:
np.isnan(A)  # tableau booléen indiquant les NaN

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [38]:
np.isnan(A).sum()  # nombre de NaN dans A

2

In [39]:
np.isnan(A).sum() / A.size  # proportion de NaN dans A

0.08

In [40]:
A[np.isnan(A)] = 0  # remplacer les NaN par 0
A

array([[-0.07770457,  1.08963016,  0.        ,  1.41866711,  1.16827314],
       [ 0.94718595,  1.08548703,  2.38222445, -0.40602374,  0.26644534],
       [-1.35571372, -0.11410253, -0.84423086,  0.70564081, -0.39878617],
       [-0.82719653, -0.4157447 , -0.52451219,  0.81310127, -0.22925063],
       [ 2.16171737, -0.95693143,  0.06731083,  0.        , -0.45688133]])

# Bonus Algebre linéaire

In [41]:
A = np.ones((3,2))
B = np.ones((2,3))
A

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
A.T

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
A.T.shape

(2, 3)

In [45]:
A.dot(B)  # produit matriciel de A et B

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [46]:
B.dot(A)  # produit matriciel de B et A

array([[3., 3.],
       [3., 3.]])

In [47]:
A = np.random.randint(0,10,[5,5])
A

array([[0, 3, 5, 9, 4],
       [4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3],
       [7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5]])

In [48]:
np.linalg.det(A)  # déterminant de A

-528.0

In [49]:
np.linalg.inv(A)  # inverse de A

array([[ 0.81818182, -1.20075758, -0.64015152,  1.01893939,  0.24621212],
       [-0.90909091,  1.53787879,  0.50757576, -0.9469697 , -0.31060606],
       [-0.45454545,  0.51893939,  0.50378788, -0.47348485, -0.15530303],
       [ 0.18181818,  0.03409091, -0.19318182,  0.14772727, -0.07954545],
       [ 1.09090909, -1.87878788, -0.57575758,  0.96969697,  0.60606061]])

In [50]:
np.linalg.pinv(A)  # pseudo-inverse de A

array([[ 0.81818182, -1.20075758, -0.64015152,  1.01893939,  0.24621212],
       [-0.90909091,  1.53787879,  0.50757576, -0.9469697 , -0.31060606],
       [-0.45454545,  0.51893939,  0.50378788, -0.47348485, -0.15530303],
       [ 0.18181818,  0.03409091, -0.19318182,  0.14772727, -0.07954545],
       [ 1.09090909, -1.87878788, -0.57575758,  0.96969697,  0.60606061]])

In [51]:
np.linalg.eig(A)  # valeurs et vecteurs propres de A

EigResult(eigenvalues=array([21.12266557, -8.54866807,  0.33494657,  2.30708262,  3.78397331]), eigenvectors=array([[ 0.43402088,  0.74989756, -0.44742344, -0.13363145, -0.10937248],
       [ 0.44147921,  0.01373897,  0.52393067, -0.20452851,  0.03490722],
       [ 0.49304585,  0.01154926,  0.23802451,  0.03709995, -0.28826788],
       [ 0.3874301 , -0.59509834, -0.01939405, -0.38239732, -0.29859625],
       [ 0.47278503, -0.28842586, -0.68430777,  0.89034072,  0.90253036]]))

# Exercice

In [52]:
A = np.random.randint(0,100,[10,5])

moyenne = A.mean(axis=0)
ecart_type = A.std(axis=0)

A_normalised = (A - moyenne) / ecart_type

A_normalised

array([[ 1.26497611, -1.18053114,  0.36649721, -0.52052503, -0.32875454],
       [-0.56486355,  2.00177019, -1.28978825,  1.3449404 ,  0.02191697],
       [ 0.58873102, -0.46194697,  1.17701988, -1.6036985 , -1.38076906],
       [-0.76375916,  0.80412991, -0.58498593,  0.17150247, -1.73144057],
       [ 1.42409261,  0.94100308, -0.16210453,  1.22458779,  1.11776543],
       [ 0.78762664,  0.39351038,  2.09326289, -1.00193546,  1.73144057],
       [-0.4853053 , -0.2566372 , -0.90214697, -0.37008427,  0.72325998],
       [ 0.11138154,  0.05132744, -1.04310744,  0.98388257,  0.06575091],
       [-2.0366911 , -1.11209455,  0.40173732,  0.80335366, -0.41642242],
       [-0.32618881, -1.18053114, -0.05638419, -1.03202361,  0.19725272]])