In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.linear_model import SGDClassifier
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.pipeline import make_union,make_pipeline
from sklearn.model_selection import train_test_split,GridSearchCV

In [3]:
x = np.array([[10,3],
              [0,4],
              [5,3],
              [np.nan,3]
              ])

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit_transform(x)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

In [4]:
x_test = np.array([[12,5],
                   [40,2],
                   [5,5],
                   [np.nan,np.nan]
                   ])

imputer.transform(x_test)

array([[12.  ,  5.  ],
       [40.  ,  2.  ],
       [ 5.  ,  5.  ],
       [ 5.  ,  3.25]])

In [6]:
x = np.array([[1,100],
              [3,20],
              [1,15],
              [np.nan,20]
              ])

inputer = KNNImputer(n_neighbors=1)
inputer.fit_transform(x)


array([[  1., 100.],
       [  3.,  20.],
       [  1.,  15.],
       [  3.,  20.]])

In [ ]:
x = np.array([[1,100],
              [3,20],
              [1,15],
              [np.nan,np.nan]
              ])

MissingIndicator().fit_transform(x)

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])

In [11]:
pipeline = make_union(
    SimpleImputer(strategy="constant", fill_value=-99),
    MissingIndicator()
)

pipeline.fit_transform(x)

array([[  1., 100.,   0.,   0.],
       [  3.,  20.,   0.,   0.],
       [  1.,  15.,   0.,   0.],
       [-99., -99.,   1.,   1.]])

# Bonnus IterativeImputer

In [15]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer



x = np.array([[1,100],
              [3,20],
              [1,15],
              [np.nan,20]
              ])

inputer = IterativeImputer()
inputer.fit_transform(x)

array([[  1.        , 100.        ],
       [  3.        ,  20.        ],
       [  1.        ,  15.        ],
       [  1.70496649,  20.        ]])

# Retour au cours

In [21]:
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [23]:
x = titanic[["pclass","age"]]
y = titanic["survived"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5)


In [24]:
model = make_pipeline(KNNImputer(),SGDClassifier())

In [25]:
params ={
    "knnimputer__n_neighbors":[1,2,3,4],
    "sgdclassifier__alpha":[0.1,0.5,1],
    "sgdclassifier__penalty":["l1","l2"]
}

In [26]:

grid = GridSearchCV(model,param_grid=params,cv=5)

In [27]:
grid.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('knnimputer', KNNImputer()),
                                       ('sgdclassifier', SGDClassifier())]),
             param_grid={'knnimputer__n_neighbors': [1, 2, 3, 4],
                         'sgdclassifier__alpha': [0.1, 0.5, 1],
                         'sgdclassifier__penalty': ['l1', 'l2']})

In [28]:
grid.best_params_

{'knnimputer__n_neighbors': 4,
 'sgdclassifier__alpha': 0.1,
 'sgdclassifier__penalty': 'l2'}