In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3])

A

array([1, 2, 3])

In [3]:
A.ndim

1

In [4]:
A.shape

(3,)

In [5]:
B = np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
B.ndim

2

In [7]:
B.shape

(3, 2)

In [8]:
type(B.shape)

tuple

In [9]:
C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
C.size

12

In [11]:
D = np.full((2,3),9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [12]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
np.linspace(0,10,20,dtype=np.float64)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
np.linspace(0,10,20,dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [18]:
A = np.zeros((3,2))
B = np.ones((3,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
C = np.hstack((A,B))
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [21]:
C.shape

(3, 4)

In [22]:
D = np.vstack((A,B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
D.shape

(6, 2)

In [24]:
np.concatenate((A,B),axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np.concatenate((A,B),axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [26]:
D.size

12

In [27]:
D = D.reshape(3,4)
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
A = np.array([1,2,1])
A.shape

(3,)

In [30]:
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)

In [32]:
A = A.squeeze()
A.shape

(3,)

In [33]:
D = D.ravel()
D

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [34]:
D.shape

(12,)

# Exercice

In [35]:
def initialisation(m,n):
    matrice = np.random.randn(m, n)
    biais = np.ones((m,1))
    return np.concatenate((matrice,biais), axis=1)

In [36]:
initialisation(3,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433,  1.        ],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574,  1.        ],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  1.        ]])