In [23]:
import numpy as np

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
A[0,0]

1

In [26]:
A[0,1]

2

In [27]:
A[1,1]

5

In [28]:
A[:,0]

array([1, 4, 7])

In [29]:
A[0,:]

array([1, 2, 3])

In [30]:
A[0]

array([1, 2, 3])

In [31]:
A[1]

array([4, 5, 6])

In [32]:
A[2]

array([7, 8, 9])

In [33]:
A[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [34]:
B = A[0:2,0:2]
B.shape

(2, 2)

In [35]:
A[0:2,0:2] = 10
A

array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [36]:
A[:,1:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [37]:
A[:,-2:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [38]:
B = np.zeros((4,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
B[1:3,1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [40]:
C = np.zeros((5,5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
C[::2,::2] = 1
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [42]:
A = np.random.randint(1,10,[5,5])
A

array([[5, 8, 9, 4, 5],
       [2, 8, 7, 9, 2],
       [3, 5, 9, 2, 6],
       [1, 1, 3, 6, 7],
       [8, 7, 9, 6, 7]])

In [43]:
A<5

array([[False, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True, False, False,  True, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [44]:
A[A<5] = 10
A

array([[ 5,  8,  9, 10,  5],
       [10,  8,  7,  9, 10],
       [10,  5,  9, 10,  6],
       [10, 10, 10,  6,  7],
       [ 8,  7,  9,  6,  7]])

In [45]:
A = np.random.randint(1,10,[5,5])
A

array([[9, 5, 4, 7, 1],
       [5, 7, 6, 6, 3],
       [5, 1, 8, 2, 2],
       [1, 8, 4, 3, 5],
       [4, 2, 6, 9, 2]])

In [46]:
A[(A < 5) & (A>2)] = 10
A

array([[ 9,  5, 10,  7,  1],
       [ 5,  7,  6,  6, 10],
       [ 5,  1,  8,  2,  2],
       [ 1,  8, 10, 10,  5],
       [10,  2,  6,  9,  2]])

In [47]:
A = np.random.randint(0,255,[1024,720])
A

array([[176,  56,   8, ...,  24,  20, 165],
       [200, 205,  13, ..., 226,  77,   4],
       [174, 199, 111, ..., 186, 107, 120],
       ...,
       [132,  91, 250, ...,  84,  60,  75],
       [ 64, 247, 187, ..., 147,  61,  72],
       [140,  22,  96, ..., 214,  60, 244]])

In [48]:
A[A > 200] = 255
A

array([[176,  56,   8, ...,  24,  20, 165],
       [200, 255,  13, ..., 255,  77,   4],
       [174, 199, 111, ..., 186, 107, 120],
       ...,
       [132,  91, 255, ...,  84,  60,  75],
       [ 64, 255, 187, ..., 147,  61,  72],
       [140,  22,  96, ..., 255,  60, 255]])

In [49]:
A[A<5]

array([4, 0, 3, ..., 2, 3, 1])

In [50]:
A[A<5].shape

(14513,)